### ISSUE TITLE
Create a standalone desktop app

### ISSUE THREAD

**Issue by jhicken** [ryanio/focusmusic.fm#21]
I personally don't like using the in browser app. For a few reasons. The biggest being if I jump on a conference call with someone. I have to track down the tab in my browser that is musicing. 

Have you thought about wrapping this in a standalone electron or nwjs app? And tying it to the pause play buttons?

Nice work BTW. I am super appreciative.

**Comment by ryanio** [comment]
Thanks @jhicken. Actually @nmaggioni just added MediaSession support in https://github.com/ryanio/focusmusic.fm/pull/22 so that may alleviate some of your woes, as you should be able to use the play/pause buttons on your keyboard to control the site now. Give it a try and let me know what you think.

I don't have the time right now to work on a standalone desktop app, but if you'd be interested in developing one using something like electron, I'd be happy to give you a brief explanation of how the backend API works that you could use!

I will close this issue for now but please feel free to open a new one if you have anything specific you'd like to discuss.
